# --- Build Stage ---
FROM node:18 AS build

# Set working directory
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the application code
COPY client/ .

# Build the app for production
RUN ng build --optimization=true

# --- Serve Stage ---
FROM nginx:alpine

# Copy Nginx configuration
COPY client/nginx.conf /etc/nginx/nginx.conf

# Copy the built app to Nginx serve folder
COPY --from=build /app/dist/addresses-dashboard/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
