# Use the official Node.js image as a base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY server/package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY server/ ./

# Copy the addresses.json file to the working directory
COPY addresses.json ./

# Expose port 8080 for the Express server to listen on
EXPOSE 8080

# Define the command to run the application
CMD ["npm", "start"]
